# Site settings
title: HeurekaDevs
email: todo@heureka.cz
description: Vojáci vývoje bránící čistotu kódu v Heurece
baseurl: "" # the subpath of the site
url: "http://www.heurekadevs.cz" # the base hostname & protocol for the site

# Social media
twitter_username: heurekadevs
github_username: heureka
youtube_username: heureka
instagram_username: heurekacz

# Emailing via getsimpleform.com
email_token_about_us: a7ffa4332b70ffb1d036f14465e5e722
email_token_academy: a7ffa4332b70ffb1d036f14465e5e722
email_token_career: a7ffa4332b70ffb1d036f14465e5e722

# Build settings
markdown: kramdown

# Additional settings
include: ["_pages"] # to have pages in separate dir
permalink: /:title/ # build URL from title if no permalink supplied

