# Site settings
title: HeurekaDevs
email: todo@heureka.cz
description: Vývojáři z Heureky o vývoji v Heurece
baseurl: "" # the subpath of the site
url: "https://www.heurekadevs.cz" # the base hostname & protocol for the site

# Social media
twitter_username: heurekadevs
github_username: heureka
youtube_username: heureka
instagram_username: heurekadevs

# Build settings
markdown: kramdown

# Additional settings
include: ["_pages"] # to have pages in separate dir
permalink: /:title/ # build URL from title if no permalink supplied

