# Site settings
title: HeurekaDevs
email: todo@heureka.cz
description: Vojáci vývoje bránící čistotu kódu v Heurece
baseurl: "" # the subpath of the site
url: "http://www.heurekadevs.cz" # the base hostname & protocol for the site

# Social media
twitter_username: heurekadevs
github_username: heureka
youtube_username: heureka
instagram_username: heurekacz

# Emailing via getsimpleform.com
email_token_about_us: 491e7e7ec2427a434fff3e715a8c20f2
email_token_academy: 491e7e7ec2427a434fff3e715a8c20f2
email_token_career: 491e7e7ec2427a434fff3e715a8c20f2

# Build settings
markdown: kramdown

# Additional settings
include: ["_pages"] # to have pages in separate dir
permalink: /:title/ # build URL from title if no permalink supplied

